version: '2'

services:

  apigateway:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/apigateway
    hostname: apigateway
    container_name: ng-kaart-apigateway
    extra_hosts:
     - ng-kaart:${DOCKER_OUTER_HOST}
    ports:
     - 80:80

  locatorservices:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/locatorservices
    hostname: locatorservices
    container_name: ng-kaart-locatorservices

  db-locatiezoeker:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/locatiezoeker-postgres
    hostname: db-locatiezoeker
    container_name: ng-kaart-db-locatiezoeker

  locatiezoeker:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/locatiezoeker
    hostname: locatiezoeker
    container_name: ng-kaart-locatiezoeker
    links:
     - db-locatiezoeker:db

  db-locatieservices:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/locatieservices-postgres
    hostname: db-locatieservices
    container_name: ng-kaart-db-locatieservices

  locatieservices:
    image: 162510209540.dkr.ecr.eu-west-1.amazonaws.com/rood/locatieservices
    hostname: locatieservices
    container_name: ng-kaart-locatieservices
    links:
     - db-locatieservices:db
